### ISSUE TITLE
Surprisingly I found that TPU had official support on PyTorch, but I wonder which version is it corresponding to?

### ISSUE THREAD

**Issue by CyFeng16** [tensorflow/tfrc#2]
Happy to see that Google has always kept the mind open.
I have been able to choose PyTorch support when creating a new TPU node.
The news is very exciting but found no relevant reports or blogs.
I would like to try new things and feedback, once I know the PyTorch version(XLA compiler supported).
[tpu-pytorch.png](https://drive.google.com/file/d/1QHfL7tLNfyZ7JG2-iqgBpWF3pU_5fDDC/view?usp=sharing)

**Comment by chrislarkin** [comment]
We're happy to hear that you're excited!

As noted in the issue you've referenced, [pytorch/xla](https://github.com/pytorch/xla) will be the repo to watch. I'm not aware of any official announcements or blog posts yet, but it is still in the early stages so it seems likely that these will arrive eventually. The TFRC team will be reaching out to program members that have expressed interest in PyTorch as well, so keep an eye on your inbox. :)
