### ISSUE TITLE
Access to TFRC

### ISSUE THREAD

**Issue by alighofrani95** [tensorflow/tfrc#3]
Hello all Dears,

How can we access free tpu via TFRC for pre-training BERT language Model on a specific language?

the link below explains that we have to sign up here: https://services.google.com/fb/forms/tpusignup/ , but it seems that it's a dead URL.
https://ai.googleblog.com/2017/05/introducing-tensorflow-research-cloud.html

Nothing happened By Apply now at https://www.tensorflow.org/tfrc

**Comment by chrislarkin** [comment]
Apologies for the delay - this repo isn't generally monitored for issues as we don't host any code here. :)

If you still have issues relating to your application, please drop us an email at trc-support@google.com.
